### ISSUE TITLE
Referenced libraries are missing

### ISSUE THREAD

**Issue by quinn-dev** [sleepdiary/dashboard#1]
In `public/index.html`, the following libraries are referenced:
https://github.com/sleepdiary/dashboard/blob/d98e67c75d92ba30631486a2199ad6fe64f4fd99/public/index.html#L11-L14

However, they aren't part of the repository nor are they loaded at build time. Without them, the web application fails to load.

Upon further inspection, it appears as if each library is built by GitHub actions and then served through GitHub pages, which is why the Dashboard at https://sleepdiary.github.io/dashboard is functional. But this approach does not work for local development or for forks of the project (unless they also fork all of the dependent libraries, which is a bad idea).

There are multiple possible solutions for this problem. As a quick solution, this issue could be temporarily fixed by replacing the relative paths in `public/index.html` and `public/info-worker.js` with absolute paths to https://sleepdiary.github.io/.

**Comment by andrew-sayers** [comment]
Hmm, good point.  It does need to be possible to work with local/forked copies of the library (e.g. to develop a new library feature and view it in the dashboard at the same time), but yes that shouldn't be the default.

How about adding a webpack option like `script_url` that normally points to https://sleepdiary.github.io/ but can be overridden with an environment variable?  So lines like the above would look something like:

    <script src="<%= htmlWebpackPlugin.options.script_url %>/library/sleepdiary-library.min.js"></script>

**Comment by quinn-dev** [comment]
I can confirm that 98d16c8 fixes the issue, and it also fixes [another issue](https://stackoverflow.com/a/57686677) I encountered regarding the use of relative paths.
