### ISSUE TITLE
Removing external dependencies

### ISSUE THREAD

**Issue by quinn-dev** [sleepdiary/dashboard#7]
Currently the dashboard loads external dependencies from various CDNs:
https://github.com/sleepdiary/dashboard/blob/bfa6ee09d8d6516201c61ed983853e589e464c29/public/index.html#L9-L10
https://github.com/sleepdiary/dashboard/blob/bfa6ee09d8d6516201c61ed983853e589e464c29/public/index.html#L15-L17

Each of these CDNs may collect and share user data. In particular, the privacy policies of [Google](https://policies.google.com/privacy), [Cloudflare](https://www.cloudflare.com/privacypolicy/) and [jsdelivr](https://www.jsdelivr.com/terms/privacy-policy-jsdelivr-net) apply every time the user visits the dashboard, in addition to GitHub's own [privacy policy](https://docs.github.com/en/github/site-policy/github-privacy-statement). Google and Cloudflare in particular are known to have a more than questionable track record when it comes to privacy.

While GitHub's privacy policy will apply for as long as we use GitHub pages, exposing users to Google, Cloudflare and jsdelivr is not a necessity, and removing those CDNs would significantly improve the privacy-friendliness of the application.

Since the web app already uses `@vue/cli-service`, which in turn uses webpack, the dependencies currently being loaded via CDN can be added as npm dependencies instead and get bundled automatically during the build process. I have already added ExcelJS, jsPDF, the Roboto font and MaterialDesignIcons as npm dependencies and removed the corresponding CDN references (see #6). I manually checked whether all affected functionality still works as intended and couldn't find any issues.

The only dependency I haven't switched over to npm yet is `sql.js`. As far as I can tell, it's not used in the `dashboard` application and a dependency of `sleepdiary/library`'s preprocessor instead. But the preprocessor [loads the dependency itself](https://github.com/sleepdiary/library/blob/85f4dc14af6d41b3df62a43ec099219b1eaa3a3b/src/ActivityLog/preprocessor.js#L2-L10), so I don't see why it's also loaded in the `dashboard` application.

Furthermore, I noticed that all libraries that the dashboard application depends on - `libary`, `report` and `info` - load their own dependencies at runtime. I don't see any benefit but various downsides to this approach and would therefore recommend bundling each library's dependencies at runtime, just as the dependencies currently loaded via CDN do.

**Comment by andrew-sayers** [comment]
There's a lot of things to discuss here, and actually there's a lot of *types* of issues to discuss.  To keep things from getting too messy, I'll talk about...

* issues of principle on this page
* general code style in the [the associated PR](https://github.com/sleepdiary/dashboard/pull/6)
* specific lines of code in [comments on the commit(s)](https://github.com/sleepdiary/dashboard/pull/6/commits/ef4230ba497dabe7403f4a48c153777e7a50489e)

Obviously, the downside of importing third-party stuff is that pages are slower to load.  We won't know how big a problem that is until we deploy it and see how the page performs, so I'm minded to accept this, try it out, and revert it if necessary.

As you say, `sql.js` is used by the preprocessor.  The `<script>` tag and all those after it are included there to make sure they load *after* everything that's needed to display the first screen, but *before* they're actually needed (and could slow the user down while they wait for a download).  Simply loading them like a normal `npm` dependency doesn't seem like it would solve that problem, but I'd prefer to just leave them out of this issue and come back to them when we've got a better handle on the build system overall.

Having said that, how about we add a comment above `<script ...sql.js...>` something like:

    

That would make it clearer what's going on, without prejudicing any later conversation.

**Comment by andrew-sayers** [comment]
Closing this in favour of the above issue - any further discussion can go there for now.
